### ISSUE TITLE
Remove operation on sample applications and configurations don't work anymore

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery-istio#143]
**Description**
The delete operation on any of the cards don't work anymore.

**Comment by leecalcote** [comment]
@utkarsh-pro this isn't true any longer, correct? This bug has been fixed in v0.4.10, I believe.

**Comment by utkarsh-pro** [comment]
>@utkarsh-pro this isn't true any longer, correct? This bug has been fixed in v0.4.10, I believe.  

Yes @leecalcote, delete operation is now functional on both sample applications and custom operations.

**Comment by leecalcote** [comment]
Excellent.
