### ISSUE TITLE
ReleaseDrafter should use RELEASEDRAFTER_PAT instead of GH_Token

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery-istio#146]
**Description**

It is a pain to copy-paste and manually makes releases, which completely is overwork gave we have releaseDrafter already installed.

**Expected Behavior**

Make releaseDrafter use Personal_Pat Token.

**Change to be made**

Change this line https://github.com/layer5io/meshery-istio/blob/33dac290d077df03c62b7e0704aa342da7f0ead0/.github/workflows/release-drafter.yml#L18 to 
```yaml
          GITHUB_TOKEN: ${{ secrets.RELEASEDRAFTER_PAT }}
```

**Comment by crustyy** [comment]
Can i work on this?
