### ISSUE TITLE
Operation: "Check configuration" failing in v0.4.10

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-istio#160]
**Description**
When Istio is **not deployed**, running "check configuration" fails with the error below.

The user receives no feedback in Meshery UI.

**Logs**
```
meshery-istio_1     | E1205 00:02:54.003782       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.8/tools/cache/reflector.go:125: Failed to list *v1beta1.VirtualService: the server could not find the requested resource (get virtualservices.networking.istio.io)
```

**Enviroment:**
 - Version: v0.4.10

**Comment by utkarsh-pro** [comment]
@leecalcote "Check Configuration" is not yet available in the latest version neither it is visible for me when I run my local adapter. Although when I tested out layer5/meshery-istio:edge-latest docker image, it looked like it is running an older version.

List of functionalities that should be visible in the UI with v0.4.10:
1. Install/Uninstall Istio
2. Install/Uninstall Emojivoto, HTTPBin, Image Hub, Istio Book Info sample applications
3. Label Namespace for Automatic Sidecar Injection
4. SMI Conformance (Not functional at the moment)
5. Apply/Remove custom configuration.

**Comment by leecalcote** [comment]
Thanks for this, @utkarsh-pro. Is work in-progress on configuration checks (istio vet)?

**Comment by utkarsh-pro** [comment]
> Thanks for this, @utkarsh-pro. Is work in-progress on configuration checks (istio vet)?

@leecalcote, right now I am working on adding "addons" (like prometheus monitoring, kiali dashboard, etc) to the istio adapter. Will add configuration checks to the list now :notebook:
