### ISSUE TITLE
[CI] Docker Hub description update failure

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-istio#209]
**Description**
A recent release of this adapter failed in its step to update the description in docker hub. See https://github.com/layer5io/meshery-istio/runs/2509268789?check_suite_focus=true

**Screenshots**
<img width="971" alt="Screen Shot 2021-05-05 at 7 49 11 AM" src="https://user-images.githubusercontent.com/7570704/117143472-81c74b00-ad76-11eb-88d0-148e979f85c1.png">

**Comment by josephmidura** [comment]
I'm confused about the scope of this issue. Is this meant to be exploratory work to see if this bug is reproducible?

**Comment by leecalcote** [comment]
Here’s a link to the Docker Hub repo in question - https://hub.docker.com/r/layer5/meshery-istio

**Comment by leecalcote** [comment]
I just re-ran the build here and it passed. It seems that the prior failure was just a fluke.

**Comment by ramrodo** [comment]
Considered a Flaky test. Open it if you consider it.
