### ISSUE TITLE
[Build] Local builds failing with undefined: unix.SYS_IOCTL

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-istio#212]
**Description**
Using `make run` to build from `master` produces the following error:

```
➜  meshery-istio git:(master) make run
DEBUG=true GOPROXY=direct GOSUMDB=off go run main.go
# github.com/docker/docker/pkg/term
../go/pkg/mod/github.com/docker/docker@v1.4.2-0.20200203170920-46ec8731fbce/pkg/term/tc.go:13:28: undefined: unix.SYS_IOCTL
../go/pkg/mod/github.com/docker/docker@v1.4.2-0.20200203170920-46ec8731fbce/pkg/term/tc.go:18:28: undefined: unix.SYS_IOCTL
../go/pkg/mod/github.com/docker/docker@v1.4.2-0.20200203170920-46ec8731fbce/pkg/term/termios_bsd.go:24:31: undefined: unix.SYS_IOCTL
../go/pkg/mod/github.com/docker/docker@v1.4.2-0.20200203170920-46ec8731fbce/pkg/term/termios_bsd.go:37:31: undefined: unix.SYS_IOCTL
```

**Comment by utkarsh-pro** [comment]
@leecalcote, this looks like a MacOS only issue. Although I went through the source code of this particular dependency and it looks like that 
```diff
-       github.com/docker/docker => github.com/moby/moby v17.12.0-ce-rc1.0.20200618181300-9dc6525e6118+incompatible
+       github.com/docker/docker => github.com/moby/moby v20.10.6+incompatible
```

in go.mod should resolve this issue as in this latest release they got rid of `tc.go` which was using the unsupported system call.

@kumarabd, can you please confirm on your machine if this fixes the issue? I ran some tests on my system after making this change locally just to verify if it is not breaking change for us. The manual tests involved:
1. Creating meshkit k8s client
2. Installing helm chart
3. Uninstalling helm chart
4. Applying manifest

**Comment by leecalcote** [comment]
@bartkalanski ran into this same issue while building the meshery-istio adapter, too. // @vijcheru

**Comment by leecalcote** [comment]
@Ayush-Khandelwal-007 could you also confirm that this addresses the issue on your machine?

**Comment by kumarabd** [comment]
> @leecalcote, this looks like a MacOS only issue. Although I went through the source code of this particular dependency and it looks like that
> 
> ```diff
> -       github.com/docker/docker => github.com/moby/moby v17.12.0-ce-rc1.0.20200618181300-9dc6525e6118+incompatible
> +       github.com/docker/docker => github.com/moby/moby v20.10.6+incompatible
> ```
> 
> in go.mod should resolve this issue as in this latest release they got rid of `tc.go` which was using the unsupported system call.
> 
> @kumarabd, can you please confirm on your machine if this fixes the issue? I ran some tests on my system after making this change locally just to verify if it is not breaking change for us. The manual tests involved:
> 
> 1. Creating meshkit k8s client
> 2. Installing helm chart
> 3. Uninstalling helm chart
> 4. Applying manifest

Yes adding `github.com/docker/docker => github.com/moby/moby v17.12.0-ce-rc1.0.20200618181300-9dc6525e6118+incompatible` should resolve this issue. @utkarsh-pro

**Comment by kumarabd** [comment]
Closing as this is not an issue, but a dependency to take care of in Mac.
