### ISSUE TITLE
[README] Need to fix Slack badge

### ISSUE THREAD

**Issue by amino19** [layer5io/meshery-istio#237]
**Description**

<a href="https://github.com/layer5io/meshery-istio/blob/master/README.md">README.md</a> is the first file one should read when starting a new project. For attractive look, we added some badges also.
But, there's a Slack badge failing, need to fix that. 
 
### Screenshot

**Current Behavior**

![image](https://user-images.githubusercontent.com/75872316/122452524-fa9d0200-cfc6-11eb-86b6-2f68ce7ff948.png)

**Desired Behavior**
![image](https://user-images.githubusercontent.com/75872316/122452420-dd683380-cfc6-11eb-9caf-8313818fa114.png)

**Environment:**
 - OS: any [e.g. Ubuntu]
 - Browser: any [e.g. Chrome, Safari]
 - Version: any [e.g. 22]
 - Device: any [e.g. laptop, iPhone 8]

**Comment by adithyaakrishna** [comment]
Assigning Myself on this 😶
