### ISSUE TITLE
README: Add hyperlinks to badges

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-istio#34]
**Description**
Some of the badges in this repos readme are missing informative hyperlinks.

**Desired Behavior**
The badges (and their links) that are used in the [Meshery repo's README](https://github.com/layer5io/meshery/blob/master/README.md) are a great example of how the badges in this repo can be improved.

**Comment by LeTrovoes** [comment]
Mind if I take this?

**Comment by leecalcote** [comment]
Nice work, @LeTrovoes. Thank you!
