### ISSUE TITLE
Integrate all contributors

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery-istio#45]
**Current Behavior**

**Comment by girishranganathan** [comment]
@all-contributors please add @gunjanmimo for tool

**Comment by gunjanmimo** [comment]
@all-contributors please add @venilnoronha for tool

**Comment by gunjanmimo** [comment]
@all-contributors please add @leecalcote for tool

**Comment by gunjanmimo** [comment]
@all-contributors please add @girishranganathan  for tool

**Comment by gunjanmimo** [comment]
@all-contributors please add @ashiscs  for tool

**Comment by gunjanmimo** [comment]
@all-contributors please add @subhamkrai  for tool

**Comment by gunjanmimo** [comment]
@all-contributors please add @LeTrovoes  for tool

**Comment by gunjanmimo** [comment]
@all-contributors please add @antweiss  for tool

**Comment by gunjanmimo** [comment]
@all-contributors please add @jesuslerma  for tool

**Comment by gunjanmimo** [comment]
@all-contributors please add @Harshini-M  for maintainer

**Comment by leecalcote** [comment]
All, my perspective it that this tool isn't flexible enough for what we need to recognize our code and non-code contributors. Barring hearing otherwise from others, I'll close this issue this week.

**Comment by leecalcote** [comment]
@gunjanmimo, given the community's decision to use meshery.io/community instead of All Contributors, will you close this issue when ready?
